typography_spectrum: 0.4014337135013193
color:
  brandStrength: 0.7645229029003531
  lightness: 0.24572642147541046
  saturation: 0.40275185531936586
  rhythmicContrast: 0.47842784505337477
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
layout_spectrum: 0.0496670154388994
author:
  name: Dennis McGraw
  email: dennis@avaxmedia.com
  url: 'http://www.avaxmedia.com'
name: Avax Media
title: A Web Agency That Thinks Differently
description: 'Design, Google Adwords, Social Media '
