layout_spectrum: 0.9
description: 'Design, Google Adwords, Social Media '
name: Avax Media
title: A Web Agency That Thinks Differently
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.4014337135013193
color:
  brandStrength: 0.7645229029003531
  saturation: 0.4027518553193659
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  lightness: 0.2457264214754105
  rhythmicContrast: 0.4784278450533748
